Update build-test.yml

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -31,17 +31,17 @@ jobs:
         docker build -t hexo-site . || { echo "Docker build failed"; exit 1; }
         docker run -i --name hexo-container hexo-site npm run build > build_output.log 2>&1 || { 
           echo "Build process failed. Container logs:"; 
-          docker logs hexo-container;
+          docker -i logs hexo-container;
           echo "Build output:";
           cat build_output.log;
           exit 1;
         }
 
         echo "Contents of /app directory:"
-        docker exec hexo-container ls -la /app
+        docker -i exec hexo-container ls -la /app
 
         # docker exec hexo-container ls -la /app;
-        docker cp hexo-container:/app/public ./public || { echo "Failed to copy files from container";  exit 1; }
+        docker -i cp hexo-container:/app/public ./public || { echo "Failed to copy files from container";  exit 1; }
         
         docker rm hexo-container
         
