Update build-test.yml

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -28,20 +28,20 @@ jobs:
           exit 1
         fi
         
-        docker build -i hexo-site . || { echo "Docker build failed"; exit 1; }
-        docker run -i --name hexo-container hexo-site npm run build > build_output.log 2>&1 || { 
+        docker build -t hexo-site . || { echo "Docker build failed"; exit 1; }
+        docker run -t --name hexo-container hexo-site npm run build > build_output.log 2>&1 || { 
           echo "Build process failed. Container logs:"; 
-          docker -i logs hexo-container;
+          docker -t logs hexo-container;
           echo "Build output:";
           cat build_output.log;
           exit 1;
         }
 
         echo "Contents of /app directory:"
-        docker -i exec hexo-container ls -la /app
+        docker -t exec hexo-container ls -la /app
 
         # docker exec hexo-container ls -la /app;
-        docker -i cp hexo-container:/app/public ./public || { echo "Failed to copy files from container";  exit 1; }
+        docker -t cp hexo-container:/app/public ./public || { echo "Failed to copy files from container";  exit 1; }
         
         docker rm hexo-container
         
